# manifests/cluster-secret-store.yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1  # Replace with your AWS region
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-system
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-parameter-store
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1  # Replace with your AWS region
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-system
---
# Multi-region support example
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager-eu
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-system
