# manifests/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::211125576793:role/ExternalSecretsRole
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/managed-by: argocd
