# examples/external-secret-example.yaml
# Example 1: Database credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: myapp  # Your application namespace
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: database-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        DB_USERNAME: "{{ .username }}"
        DB_PASSWORD: "{{ .password }}"
        DB_HOST: "{{ .host }}"
        DB_PORT: "{{ .port }}"
        DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@{{ .host }}:{{ .port }}/{{ .database }}"
  data:
  - secretKey: username
    remoteRef:
      key: myapp/database
      property: username
  - secretKey: password
    remoteRef:
      key: myapp/database
      property: password
  - secretKey: host
    remoteRef:
      key: myapp/database
      property: host
  - secretKey: port
    remoteRef:
      key: myapp/database
      property: port
  - secretKey: database
    remoteRef:
      key: myapp/database
      property: database
---
# Example 2: API Keys from Parameter Store
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-keys
  namespace: myapp
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: api-keys-secret
    creationPolicy: Owner
  data:
  - secretKey: STRIPE_API_KEY
    remoteRef:
      key: /myapp/stripe/api-key
  - secretKey: SENDGRID_API_KEY
    remoteRef:
      key: /myapp/sendgrid/api-key
  - secretKey: JWT_SECRET
    remoteRef:
      key: /myapp/jwt/secret
---
# Example 3: Complete secret sync
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-config
  namespace: myapp
spec:
  refreshInterval: 120s
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: app-config-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: myapp/config
