apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-operator-appset
  namespace: external-secrets
spec:
  generators:
  - list:
      elements:
      - cluster: https://kubernetes.default.svc
        namespace: external-secrets-system
        name: external-secrets-operator
  template:
    metadata:
      name: '{{name}}'
      namespace: external-secrets
    spec:
      project: default
      source:
        repoURL: https://charts.external-secrets.io
        chart: external-secrets
        targetRevision: 0.14.0
        helm:
          releaseName: external-secrets
          values: |
            installCRDs: true
            replicaCount: 2
            serviceAccount:
              create: true
              name: external-secrets
              annotations:
                eks.amazonaws.com/role-arn: arn:aws:iam::767397685517:role/ExternalSecretsRole
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 10m
                memory: 32Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 65534
            webhook:
              replicaCount: 2
            certController:
              replicaCount: 2
            serviceMonitor:
              enabled: false
            podDisruptionBudget:
              enabled: true
              minAvailable: 1
      destination:
        server: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
        - /status
